apiVersion: v1
kind: Service
metadata:
  name: springboot-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: springboot-demo # must match in deployment
  ports:
    - protocol: TCP
      port: 9080 # different from targetPort/containerPort
      targetPort: 8080 # must match deployment containerPort
